# Generated by Django 3.0.10 on 2020-09-15 22:27

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wtknowledgebase.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='KbArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.StreamField([('richtext', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('quote', wagtail.core.blocks.BlockQuoteBlock()), ('page', wagtail.core.blocks.PageChooserBlock()), ('card', wagtail.core.blocks.StructBlock([('header_title', wagtail.core.blocks.RichTextBlock(required=False)), ('card_classes', wagtail.core.blocks.CharBlock(help_text="Be sure to include 'card'", required=False)), ('card_header_classes', wagtail.core.blocks.CharBlock(help_text="Be sure to include 'card-header'", required=False)), ('card_body_classes', wagtail.core.blocks.CharBlock(help_text="Be sure to include 'card-body'", required=False)), ('body', wagtail.core.blocks.StreamBlock([('richtext', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('quote', wagtail.core.blocks.BlockQuoteBlock()), ('page', wagtail.core.blocks.PageChooserBlock())]))])), ('grid_row', wagtail.core.blocks.StructBlock([('class_name', wagtail.core.blocks.CharBlock(required=False)), ('cells', wagtail.core.blocks.ListBlock(wtknowledgebase.blocks.GridCellBlock))]))])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='KbCategoryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.StreamField([('richtext', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('quote', wagtail.core.blocks.BlockQuoteBlock()), ('page', wagtail.core.blocks.PageChooserBlock()), ('card', wagtail.core.blocks.StructBlock([('header_title', wagtail.core.blocks.RichTextBlock(required=False)), ('card_classes', wagtail.core.blocks.CharBlock(help_text="Be sure to include 'card'", required=False)), ('card_header_classes', wagtail.core.blocks.CharBlock(help_text="Be sure to include 'card-header'", required=False)), ('card_body_classes', wagtail.core.blocks.CharBlock(help_text="Be sure to include 'card-body'", required=False)), ('body', wagtail.core.blocks.StreamBlock([('richtext', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('quote', wagtail.core.blocks.BlockQuoteBlock()), ('page', wagtail.core.blocks.PageChooserBlock())]))])), ('grid_row', wagtail.core.blocks.StructBlock([('class_name', wagtail.core.blocks.CharBlock(required=False)), ('cells', wagtail.core.blocks.ListBlock(wtknowledgebase.blocks.GridCellBlock))]))])),
                ('category_name', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='KbIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.StreamField([('richtext', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('quote', wagtail.core.blocks.BlockQuoteBlock()), ('page', wagtail.core.blocks.PageChooserBlock()), ('card', wagtail.core.blocks.StructBlock([('header_title', wagtail.core.blocks.RichTextBlock(required=False)), ('card_classes', wagtail.core.blocks.CharBlock(help_text="Be sure to include 'card'", required=False)), ('card_header_classes', wagtail.core.blocks.CharBlock(help_text="Be sure to include 'card-header'", required=False)), ('card_body_classes', wagtail.core.blocks.CharBlock(help_text="Be sure to include 'card-body'", required=False)), ('body', wagtail.core.blocks.StreamBlock([('richtext', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('quote', wagtail.core.blocks.BlockQuoteBlock()), ('page', wagtail.core.blocks.PageChooserBlock())]))])), ('grid_row', wagtail.core.blocks.StructBlock([('class_name', wagtail.core.blocks.CharBlock(required=False)), ('cells', wagtail.core.blocks.ListBlock(wtknowledgebase.blocks.GridCellBlock))]))])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
